import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#FFFFFF",
        "surface": "#FAF9F6",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F5F3ED",
        "surface-container": "#EBE7DD",
        "surface-container-high": "#E1DCCF",
        "surface-container-highest": "#D8D1C1",
        "surface-variant": "#EBE7DD",
        "surface-dim": "#D8D1C1",
        "surface-bright": "#FAF9F6",
        
        "on-background": "#111814",
        "on-surface": "#111814",
        "on-surface-variant": "#3C4A42",
        
        "primary": "#18221D",
        "on-primary": "#FFFFFF",
        "primary-container": "#EBE7DD",
        "on-primary-container": "#111814",
        "primary-fixed": "#18221D",
        "on-primary-fixed": "#FFFFFF",
        "primary-fixed-dim": "#2C4238",
        "on-primary-fixed-variant": "#FFFFFF",
        
        "secondary": "#966A45",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#F5F3ED",
        "on-secondary-container": "#966A45",
        "secondary-fixed": "#966A45",
        "on-secondary-fixed": "#FFFFFF",
        "secondary-fixed-dim": "#A87B56",
        "on-secondary-fixed-variant": "#FFFFFF",
        
        "tertiary": "#B88B5D",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#F5F3ED",
        "on-tertiary-container": "#B88B5D",
        "tertiary-fixed": "#B88B5D",
        "on-tertiary-fixed": "#FFFFFF",
        "tertiary-fixed-dim": "#C89E73",
        "on-tertiary-fixed-variant": "#FFFFFF",
        
        "outline": "#966A45",
        "outline-variant": "#D8D1C1",
        
        "inverse-surface": "#111814",
        "inverse-on-surface": "#FAF9F6",
        "inverse-primary": "#EBE7DD",
        
        "error": "#BA1A1A",
        "error-container": "#FFDAD6",
        "on-error": "#FFFFFF",
        "on-error-container": "#410002",
      },
      boxShadow: {
        'sm': '0 2px 4px rgba(17, 24, 20, 0.05)',
        DEFAULT: '0 4px 12px rgba(17, 24, 20, 0.08)',
        'md': '0 8px 24px rgba(17, 24, 20, 0.12)',
        'lg': '0 16px 32px rgba(17, 24, 20, 0.15)',
        'xl': '0 24px 48px rgba(17, 24, 20, 0.2)',
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "margin-tablet": "2rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
      },
      fontFamily: {
        "label-mono": ["Space Mono"],
        "headline-lg": ["Syne"],
        "headline-md": ["Syne"],
        "display-xl-mobile": ["Syne"],
        "display-xl": ["Syne"],
        "label-caps": ["Syne"],
        "headline-lg-mobile": ["Syne"],
        "headline-sm": ["Syne"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-xl": ["84px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 24s linear infinite',
      },
    },
  },
  plugins: [],
}

export default config
