import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1a1c1c",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#e7bdb2",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary": "#c8c6c5",
        "tertiary-container": "#929090",
        "inverse-on-surface": "#313030",
        "primary-container": "#ff5625",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "background": "#131313",
        "surface-container-highest": "#353534",
        "on-tertiary": "#303030",
        "surface-bright": "#3a3939",
        "on-background": "#e5e2e1",
        "surface-container": "#201f1f",
        "surface-tint": "#ffb5a0",
        "surface-container-low": "#1c1b1b",
        "on-error": "#690005",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#e2e2e2",
        "surface": "#131313",
        "primary-fixed-dim": "#ffb5a0",
        "on-primary-fixed": "#3b0900",
        "secondary-container": "#454747",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary": "#2f3131",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#454747",
        "outline": "#ad887e",
        "on-tertiary-fixed-variant": "#474746",
        "inverse-surface": "#e5e2e1",
        "secondary": "#c6c6c7",
        "outline-variant": "#5d4038",
        "surface-dim": "#131313",
        "on-secondary-container": "#b4b5b5",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-container": "#2a2a2a",
        "primary": "#ffb5a0",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#b12d00",
        "on-primary-container": "#541100",
        "on-tertiary-fixed": "#1b1b1c",
        "on-primary": "#601400",
        "primary-fixed": "#ffdbd1",
        "on-primary-fixed-variant": "#872000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "margin-tablet": "2rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
      },
      fontFamily: {
        "label-mono": ["Space Mono"],
        "headline-lg": ["Syne"],
        "headline-md": ["Syne"],
        "display-xl-mobile": ["Syne"],
        "display-xl": ["Syne"],
        "label-caps": ["Syne"],
        "headline-lg-mobile": ["Syne"],
        "headline-sm": ["Syne"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-xl": ["84px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 24s linear infinite',
      },
    },
  },
  plugins: [],
}

export default config
